### ISSUE TITLE
Hardcoded Dimensions in Diagram

### ISSUE THREAD

**Issue by endeffects** [syncfusion/blazor-samples#51]
I have a Diagram with 100% heigth and width, but i've noticed that all child elements
are using some default sizes (see screenshot).

![image](https://user-images.githubusercontent.com/13432569/61288018-8cda7100-a7c6-11e9-9e06-022b130f3741.png)

Also with the new version my pre-initialized nodes got not rendered. I can see them on the overview but not on the diagram. Dropping new nodes from palette also does not work anymore. I did not digged into it yet, maybe it is just a css mistake on my side. But it worked with v17.2.29-beta.

**Comment by gshyam93** [comment]
Hi @endeffects,

Issue : Diagram component is not rendered when the diagram size is in percentage  
 
We have fixed the reported issue and this fix included in our latest version ’17.2.0.40-beta’. Please update your package version to include this fix in your application.  
  
Regards,  
Shyam G

**Comment by endeffects** [comment]
Thank you, it works now as expected. I hope i can resume developing soon. Currently the diagram is still not interactive.

**Comment by gshyam93** [comment]
Hi endeffects,

As already mentioned, we are working on to provide better runtime interactions support in diagram based on Blazor architecture in high priority.  We will include the interactions support in diagram one by one soon. We will let you know once the interaction support provided in the diagram.

 Now, you can track the status of interaction support through below feedback link.  

Link: https://www.syncfusion.com/feedback/7441/provide-interaction-support-for-diagram

Regards,
Shyam G

**Comment by Sridhar-Narasimhan** [comment]
We have fixed this issue in the below feedback link and we are closing this item 

Feedback Link:  https://www.syncfusion.com/feedback/7441/provide-interaction-support-for-diagram
